### ISSUE TITLE
In the readme, please reference the nuget package - And fix nuget versioning.

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#13]
Also, the nuget should have the version number in the build, 
and the previous version should be kept

See the following page as an example "https://www.nuget.org/packages/NLog/"

This allows previous solutions that reference a particular version to keep compiling etc.

**Comment by Wagnerp** [comment]
I haven't updated the nuget package yet, but I will do later today.

**Comment by Wagnerp** [comment]
I have uploaded a new package with the correct versioning.  See the readme for details.

**Comment by Smurf-IV** [comment]
Just need to keep the "Old versions" so that other peoples "Old solutions" not updated, can still perform a Nuget Get refresh when the IDE opens.

**Comment by Wagnerp** [comment]
That can be done, all I need to do is to replace the binaries & increment the version number.

**Comment by Smurf-IV** [comment]
I can see the latest and the the last version.. Yay..
Now, what does 1801b mean ?

===========================================================

> KryptonToolkitSuite47 4.70.524
> Krypton Suite 4.7
> 
> Updated to work with .NET Framework 4.7.
> 
> Release version 1801b

**Comment by Wagnerp** [comment]
1801b Means a minor version. Next release might be on Sunday with the tag 1801c. It's similar to Win 10 versions. I still can't figure out why the 'UseDropShadow' property does not default to 'true' when I specified the default value to true in the code. 

Also, do you know a way to edit '.mshc' files, as I've noticed that some assets in the help file refer to Windows XP and VS 2005,  so I was wondering if there was a way to update it, to make it more relevant to Win 7/8.1/10 and VS 2017?  Been trying to find a way, but end up going in circles!

P.S I've fixed the designer bug, so it matches hard coded values.

**Comment by Smurf-IV** [comment]
I use mht format via Word (MHTML), its the easiest and still allows pictures to be embedded and all browsers support it (Even the built in WebBrowser WinForm control)
So where-ever you got the mshc from..... try and get the source 
or 
convert the original chm to mht (Plenty of online convertors - That's If you have 2007 or later MS Word to use!)

**Comment by Smurf-IV** [comment]
As for the help, It would be nice if the different dll's had different files, and also remove that dotfusticator rubbish from it as well [Check the global namespac(s) in the references section]!
