### ISSUE TITLE
Textbox MouseLeave and MouseEnter seem linked

### ISSUE THREAD

**Issue by Endimion75** [Wagnerp/Krypton-NET-4.7#14]
The mouseLeave and mouseEnter events seems to be linked.

When you enter the textbox it fires both enter and leave events.
When you leave the textbox it fires both enter and leave events.

**Comment by Wagnerp** [comment]
Hi @Endimion75,

Thanks for reporting the issue. This is a known issue where there is a routing problem. Will look into it, can you tell me what version of assembly that you are using?

**Comment by Endimion75** [comment]
Hi,

   I am using:
   name: ComponentFactory.Krypton.Toolkit
   runtime version: v4.0.30319
   version: 4.7.0.0

   I used the nuget package : KryptonSuite47e

   Is this what you asked?

**Comment by Wagnerp** [comment]
Hi @Endimion75, 

There is an updated revision here [KryptonToolkitSuite47](https://www.nuget.org/packages/KryptonToolkitSuite47/) with the version of 4.70.522. It may be because you're using a old version. Had a look at the latest code, and nothing seemed to be wrong.

**Comment by Endimion75** [comment]
Hi,

I tried to install the suggested version:

Install-Package KryptonToolkitSuite47 -Version 4.70.522

and I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'KryptonToolkitSuite47 4.70.522'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

My project is targeting version 4.7:
<TargetFrameworkVersion>v4.7</TargetFrameworkVersion>

I also tried changing to version 4.7.1 with the same result

Am I mission something?

**Comment by Wagnerp** [comment]
Hi,

Yes, I have run into this issue before, have you got any of the older versions with the 'RegisterToGAC.bat' file? If not, I can upload the associated binaries and files to this repo for download. That suppression bug was meant to be fixed a few versions back, but it seems to have been reintroduced somehow.

**Comment by Endimion75** [comment]
I want to say that I greatly appreciate the time you are taking by helping me, thank you very much.

I have found  the 'RegisterToGAC.bat' in one my my earlier downloads of the Krypton Suit.  Just to be sure I understand, you recommend to get the bins from the project source and register them in the GAC, correct?

**Comment by Smurf-IV** [comment]
FYI: I do not use GAC registration in any of my PC's for the use of the Krypton DLL's
It makes up and downgrading easier, and also when developing against new builds I just use the direct reference in the projects.
The Only downside to this, is that i have to Drag and drop the Toolkit (etc) into the IDE Toolbox each time, and the Designer dll needs to be in the references.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV,

There is an issue in version 4.70.522 whereby you can't drag & drop items to the form, as they all dock to the bottom where a timer would be.

**Comment by Wagnerp** [comment]
Hi @Endimion75,

I'm going to upload a older version '4.7.0.0' which is known to work, compiled on 11th November 2017, but may need to 'manually' alter the version number to fool Nuget into uploading it. In other words, you may see a version tag of '4.70.523' when it's really '4.7.0.0'.

**Comment by Endimion75** [comment]
Thank you very much for your help

**Comment by Wagnerp** [comment]
You should now see it in the releases tab of the repo.

**Comment by Smurf-IV** [comment]
> There is an issue in version 4.70.522 whereby you can't drag & drop items to the form, as they all dock to the bottom where a timer would be

@Wagnerp.
That would be because of the change to the Design version I warned you about in the submit..
It is a hard coded string in all of the Toolbox designer references.
Set it back to 4.70.0.0 and it will be fine.

**Comment by Wagnerp** [comment]
@Smurf-IV,

Ahh, thanks, will see to it straight away. Is it only for the toolbox items?

**Comment by Smurf-IV** [comment]
@Wagnerp,
The designer dll is only used for the IDE. To allow it to perform Form layout etc.
Does not affect the actual runtime operation for the target application. 

@Endimion75,
So, if the mouseleave stuff is triggering without a breakpoint or a messagebox getting in the way, then that may be in the ToolKit dll code somewhere, or some function that is forcing it to exit within the "Usage" application.

**Comment by Endimion75** [comment]
I tried to follow the code of the textbox leave event.  As far as I can understand, the control uses a mouse over function to determine if it is a leave or an enter and then invokes the corresponding event, but for some reason the mouse leave events gets triggered independently of that logic. 

I notice that the windows sends a message with the leave code when it should be an enter code, but I am not familiar with this pipeline so I could be misunderstanding it.

**Comment by Wagnerp** [comment]
@Smurf-IV 

Ok, I'll run some tests today. The changes will be held in the stable branch with assemblies set to 4.70.0.0. Will reset the master ASAP.

**Comment by Endimion75** [comment]
I must add that I am debugging the source from Krypton-NET-4.7.1-master on the toolkit 2015 project

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

When you refer to the Designer dll, are you referring to ComponentFactory.Krypton.Design.dll? Apologies for the confusion.

**Comment by Smurf-IV** [comment]
@Wagnerp
Correct.

**Comment by Smurf-IV** [comment]
@Endimion75 
I did the following and can concur that on mouse enter, both message events fire on mouse enter without the loss of focus !!!.....

        private void kryptonTextBox2_MouseEnter(object sender, EventArgs e)
        {
            kryptonListBox1.Items.Add("MouseEnter");
        }
        private void kryptonTextBox2_MouseLeave(object sender, EventArgs e)
        {
            kryptonListBox1.Items.Add("MouseLeave");
        }

**Comment by Wagnerp** [comment]
@Smurf-IV 

Thanks for clarifying, I've fixed it on both the .NET 4.7 and 4.7.1 repos. Automatic versions should no longer interfere with the file version of the designer dll, whilst still incrementing the versions. I've also added a big bold note to the readme saying that the designer dll must be referenced in order for the toolkit to work properly.

**Comment by Smurf-IV** [comment]
@Endimion75 
I have worked it out, bare with me..

The default MouseEnter and Mouse leaves are used by the Toolkit to draw the borders etc around the controls. The design does not know this and allows anyone to attach to those events.
AS you may know, the toolkit warps the internal controls to allow default WinForms to work (In this case a normal textbox). In order for you as a code user within WinForms to use the mouse enter and leave, you will need to attach to the new forwarded events from the internal control called TrackMouse####. e.g.:

            this.kryptonTextBox2.TrackMouseEnter += new System.EventHandler(this.kryptonTextBox2_MouseEnter);
            this.kryptonTextBox2.TrackMouseLeave += new System.EventHandler(this.kryptonTextBox2_MouseLeave);

So all is well again. Would be nice if the toolkit made this a little more obvious in the IDE designer..
BUT, the help does have the following (Now that I know what to look for!!)

  | OnTrackMouseEnter | Raises the TrackMouseEnter event.
-- | -- | --
  | OnTrackMouseLeave | Raises the TrackMouseLeave event.

**Comment by Wagnerp** [comment]
@Smurf-IV 

If I'm correct, if those are event handlers within the code, then it should be possible to alter the descriptions to make more sense.

**Comment by Smurf-IV** [comment]
They are, and they are within the help, Just not visible in the events from within the designer !!

**Comment by Endimion75** [comment]
I understand, It makes sense to me now!

Thank you so much for the clarification and the time you put into this issue.  I really appreciate it.
