### ISSUE TITLE
Create a ToolkitExt project

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#20]
I want to start a project that is based on the Toolkit, but extends it's functionality to other common usages.
e.g. 
- Better Help handler (Not sure what or how to do this one yet !)
- Command Button: ![image](https://user-images.githubusercontent.com/2418812/35695099-6bdd589c-077b-11e8-9248-2f29beafda42.png)
- Timed Message Box
- Bigger Font MessageBox
- Other MessageBox Extensions:  ![image](https://user-images.githubusercontent.com/2418812/35695352-1f134fde-077c-11e8-9894-3c034e613fb3.png)

Thoughts ?
e.g. 
- Make it a separate GitHub ?
- Better as it would integrate into the existing Designer dll (only one of them!) ?
- ....

**Comment by Wagnerp** [comment]
Hi @Smurf-IV,

Yes, that sounds great. I was going to integrate the Krypton Outlook Grid into this repo, but it might be suitable for a new extended controls repo? Also maybe a new 'Office 2016' palette? I will create a new repo named Krypton Toolkit Suite Extended for this.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV,

Just to let you know that I've created a new repo located here [Krypton-Toolkit-Suite-Extended-NET-4.7](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7). Will upload a shell project later today.
