### ISSUE TITLE
Current license needs to be in the Root on Github project(s)

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#21]
Please ensure license is shown in the root so that GitHub can expand it
e.g. https://github.com/ComponentFactory/Krypton/blob/master/LICENSE
![image](https://user-images.githubusercontent.com/2418812/35775555-a73b5b06-0982-11e8-9b00-07aab14ff7f3.png)

**And** make it use-able for "All" projects.
i.e. **not** copy-left style like _GPL_
more like _BSD 3-Clause_ or open

**Comment by Wagnerp** [comment]
Put BSD 3-Clause in

**Comment by Smurf-IV** [comment]
Thank you, I can now work on the extended stuff..

**Comment by Wagnerp** [comment]
I've started laying down some base code.
