### ISSUE TITLE
NullReferenceException with Target in PaletteRedirectDouble

### ISSUE THREAD

**Issue by NintendoPlayer** [Wagnerp/Krypton-NET-4.7#23]
Hi!

I've been using the Krytpon Components from https://github.com/ComponentFactory/Krypton.  Recently I switched over your fork because of implementation of KryptonOutlookGrid.  Now my code throws some NullReferenceException when I right click any cell of my KryptonDataGridView control.

Whenever I clicked one cell, I got a ContextMenu with some options.  But now I get this:
![null](https://user-images.githubusercontent.com/18734400/36017840-abf504da-0d79-11e8-8442-1b2178a78b7d.png)

Target is null, thats why it thows the error.  But I don't know how to solve it, or if it's a bug with the palette.

The first time I encountered this is when I right clicked a KryptonOutlookGrid, because I was trying to change my kpDGV with the OutlookGrid. 

I would appreciate some help!

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer. 

Thanks for posting your question. I can tell you that the KOG was never fully implemented into this kit. Instead both I and @Smurf-IV agreed that a new extended toolkit repo was needed. Whilst in early stages at the moment, the KOG code is complete. You can find the repo over [here](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7).

I hope this helps.

**Comment by NintendoPlayer** [comment]
The thing is that this problem also arises whenever I right click any cell on my kryptonDataGridView.

I updated my project with the extended toolkit, and it's giving me the same issue.  I don't think is something related to KOG, because the standard DGV is giving the same issue.  

I thingk that is something related to ContextMenus.  This is the stacktrace:

`   en ComponentFactory.Krypton.Toolkit.PaletteRedirectDouble.GetBackImage(PaletteBackStyle style, PaletteState state)
   en ComponentFactory.Krypton.Toolkit.PaletteBackInheritRedirect.GetBackImage(PaletteState state)
   en ComponentFactory.Krypton.Toolkit.PaletteBack.GetBackImage(PaletteState state)
   en ComponentFactory.Krypton.Toolkit.RenderStandard.DrawBack(RenderContext context, Rectangle rect, GraphicsPath path, IPaletteBack palette, VisualOrientation orientation, PaletteState state, IDisposable memento)
   en ComponentFactory.Krypton.Toolkit.ViewDrawCanvas.RenderBefore(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewManager.Paint(RenderContext context)
   en ComponentFactory.Krypton.Toolkit.ViewManager.Paint(IRenderer renderer, PaintEventArgs e)
   en ComponentFactory.Krypton.Toolkit.VisualPopup.OnPaint(PaintEventArgs e)
   en System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   en System.Windows.Forms.Control.WmPaint(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.ContainerControl.WndProc(Message& m)
   en ComponentFactory.Krypton.Toolkit.VisualPopup.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Wagnerp** [comment]
Are you using a standard system context menu strip, or a Krypton context menu?

**Comment by NintendoPlayer** [comment]
a Krytpon Context Menu

**Comment by Wagnerp** [comment]
Ahh there lies the issue. Use a normal context menu strip, I've just tested it and it works without issue. You will still get the krypton render as well. Not sure why a Krytpon Context Menu was part of the original toolkit, as I never used it.

**Comment by NintendoPlayer** [comment]
Ok, I will try it.  But when I right click the OutlookGridGroupBox the same error gets fired, and I don't even have a normal context menu show in the click event.

**Comment by Wagnerp** [comment]
Odd, is there a way that you can trace back in your code to see where it's breaking?

**Comment by Smurf-IV** [comment]
The Demo App `KryptonContextMenu Examples` falls over as well.
I'll look into it.

**Comment by Wagnerp** [comment]
Been fixed in build 553
