### ISSUE TITLE
The "KyptonRibbon" defaults to `Chrome = false`, and causes Windows 10 to not draw MainForm Title text

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#35]
Professional systems work (Because they do not modify chrome)
But in Window 10 No text is displayed (Works in Win 8.1)
But, If window is not active then the text is shown!
Build 535 -> 561 (Maybe earlier)

Active Child forms are okay just the main app.

(Still cannot upload images !)

**Comment by Smurf-IV** [comment]
I have narrowed it down to the usage of the KryptonRibbin QAT.
If an application has this then the Chrome is not drawn properly (Even ion Win 8.1), and in Win 10 it makes a mess of things

**Comment by Wagnerp** [comment]
Is this because they have changed how some of the APIs work in win10, i.e UWP apps?

**Comment by Smurf-IV** [comment]
Nope, As I stated it also causes problems in Win 8.1 Chrome .

I've just found out what it is..
Look in the Designer when the `KryptonRibbon `is selected, and it has something called "`AllowFormIntegrate`", set that to False and Chrome drawing works as expected. 
Read the Help tip (In IDE) for it and it's really confusing. I think that this should be `False `by default!

**Comment by Wagnerp** [comment]
I'll merge a change today with the default value set to `false`. Could you confirm that it's just the `KryptonRibbon` control?

**Comment by Smurf-IV** [comment]
For the cause, Yes it is. 
The issue of the MainForm in Windows 10 will still need to be sorted.

**Comment by Smurf-IV** [comment]
#37 created - Closing this with the designer fix by @Wagnerp
