### ISSUE TITLE
Mouse click on Text box does not allways work

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#4]
Using Nuget 47E.
Used to work consistently, but seems to not always fire now (i.e. will work once but never again, or not at all)

**Comment by Smurf-IV** [comment]
This worked in Krypton 4.5, must be something that has been optimised out for it to "Not always" fire.

Temporary workaround is to attach the click event to the "Internal" Winform TextBox.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Maybe it was a change when re-targeting the frameworks. Is the problem just with the KryptonTextBox control? May need to 'reset' just that control back to version 4.4.5.

**Comment by Smurf-IV** [comment]
No idea, Have not been able to spend time trying to work out what has changed yet, as it might also affect other controls' events as well :-!

**Comment by Wagnerp** [comment]
I've put the file through WinMerge, and couldn't find anything glaring. I've reinstated the 47D package, so at least users should have a working toolkit.

**Comment by Smurf-IV** [comment]
> Apologies it has taken so long, I've been building a 12 Core (24 HT) monster.

Found that the following controls never had routing for the "OnClick" method to work, so it must have been a fluke that during initial testing they appeared to work via the default message pumping.

Fix "OnClick" routing for 
  - ListBox
  - CheckedListBox
  - TextBox
  - TreeView

New Delivarable incoming once I get Git working correctly...
