### ISSUE TITLE
Versioning for installers

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.7#7]
Hi, 
Due to the way installers work, the first three numbers in the "AssemblyVersion" (etc) need to be higher than the previous triplet.
i.e. 1.2.3.### > 1.2.2 for the new version to be placed.

So, Can these Dll's be versioned in this way ?

e.g. 4.7**0**.++build.0  for .Net 4.7 
and 4.7**1**.++build.0 for .Net 4.7.1

I can do this if you want ? So that the designers get picked up correctly as well (I'm sure there is a way to use just the first p[art i.e. 4.70 in the lookup strings!)

Thoughts ?

**Comment by Wagnerp** [comment]
Yes that's fine. I could put the versioning as 4.xx.* if that works better. Of course each time you build the solution, you would get a random number i.e 4.70.2698.3658 or 4.71.8955.4548. I don't know how this would affect control classes, as these seem to be hardcoded.

As for Nuget packages, it doesn't seem to like me altering circulating packages, hence the reason for strange iterations. This is the reason why I've uploaded the created package to the repo to introduce conciseness.

**Comment by Smurf-IV** [comment]
No need for the *
I use the "[Automatic Versions](https://marketplace.visualstudio.com/items?itemName=PrecisionInfinity.AutomaticVersions)" Extension on my other projects to give a controlled release number
of YY.MM.Build.Day, and this can be altered to use a different pattern per solution/project (i.e. 4.70.Build.0)
It can be set to only increment on demand as well. so just before a delivery or something similar.
I'm checking the designer attribute now to see if it can do just 4.70

Then this may allow Nuget to have a continuous incrementing number which will please it (Not sure, never had to do that yet !)

**Comment by Wagnerp** [comment]
Ok, go ahead. I will try to see what is happening with Nuget. My main concern is that uploading new/retiring old code is constantly breaking users projects. Nuget must have a way of refreshing 'live' packages on the fly. You should see my packages list on Nuget, it's quite messy!

**Comment by Smurf-IV** [comment]
After a little frustration, it appears that the Designer attribute needs a **Fully** qualified name string.
This includes the proper version. - Damn.
BUT, as the designer is not shipped... then it does **not** _need_ to have an increasing build number :-)

So I'll do the Versioning in the Releasable (read _Installable_) Dll's and leave the designer strings alone (Once changed to 4.70.0.0)

OK ?

AS for Nuget, just do what I've seen others do, and not redact/retire anything( just comment __why__ it might not be the latest greatest thing). Also I seem to recall that Nuget has a versioning specification, and if it is not used (or some other command) there is a way of getting the "Latest" when performing a refresh on the client side.

**Comment by Wagnerp** [comment]
I could do a mass find/replace for class version numbers. This would mean that the proper version would be 4.70.0.0 for controls there is about 1,100+ entries, but won't take too long on my i7 PC.

Still looking into the packaging issue. I may stick to the a, b, c etc sequence.

**Comment by Smurf-IV** [comment]
Done, you'll have to set perform the replace of 4.70 on the 4.7.1 branch that you have.

**Comment by Smurf-IV** [comment]
The versioning settings have gone into the **csproj** files, so they should be consistent.

**Comment by Smurf-IV** [comment]
Note: I did not replace the Header values, as that still has comments about
__© Component Factory Pty Ltd 2018__
Perhaps it could be extended to include yours and my names  and include your github project url at the end ?

**Comment by Smurf-IV** [comment]
Also shouldn't the  
**© blah blah** 
have range and not the latest. i.e. 2010-2018

**Comment by Wagnerp** [comment]
Will do, do you want your real name in that field? I do always ensure to give you credit within the nuget package, but I can add your name to the Author field as well.

**Comment by Smurf-IV** [comment]
Real Name, Yes that'll be fine. I use the following in my code headers:
`//  Copyright (C) 2010-2018 Simon Coghlan (Aka Smurf-IV)`

**Comment by Wagnerp** [comment]
I'm uploading a new commit to master, feel free to change anything if necessary. My rule is be bold to change anything, but it has to be stable enough for other users to use.

**Comment by Smurf-IV** [comment]
Thanks
